attributeList = {
    # Table=student
    # key			value
    'name': ['department.name', 'student.name'],
    'studentname': ['student.name'],
    'sex': ['student.sex'],
    'gender': ['student.sex'],
    'sid': ['student.sId'],
    'sId': ['student.sId'],
    'studentid': ['student.sId'],
    'id': ['student.sId', 'department.dId'],
    'address': ['student.address'],
    'lives': ['student.address'],
    'mobile': ['student.phone'],
    'landline': ['student.phone'],
    'phone': ['student.phone'],
    'phoneno': ['student.phone'],
    'cgpa': ['student.cgpa'],
    'CGPA': ['student.cgpa'],
    'grade': ['student.cgpa'],
    'pointer': ['student.cgpa'],
    'pointers': ['student.cgpa'],
    'percentage': ['student.cgpa'],
    'marks': ['student.cgpa'],
    'scored': ['student.cgpa'],
    'score': ['student.cgpa'],
    'scores': ['student.cgpa'],
    # Table=Department
    # key			value
    'dId': ['department.dId', 'student.dId'],
    'departmentname': ['department.name'],
    'studies': ['department.name'],
    'departmentid': ['department.dId'],
    'building': ['department.buildingCode'],
    'block': ['department.buildingCode'],

    "ID": ['propuska.ID'],
    "Series": ['propuska.Series'],
    "Number": ['propuska.Number'],
    "ValidFrom": ['propuska.ValidFrom'],
    "ValidTo": ['propuska.ValidTo'],
    "Zone": ['propuska.Zone'],
    "Status": ['propuska.Status'],
    "CancelDate": ['propuska.CancelDate'],
    "global_id": ['propuska.global_id'],
    "Код": ['propuska.ID'],
    "Серия пропуска": ['propuska.Series'],
    "Номер пропуска": ['propuska.Number'],
    "Действует с": ['propuska.ValidFrom'],
    "Действует по": ['propuska.ValidTo'],
    "Зона действия": ['propuska.Zone'],
    "Статус": ['propuska.Status'],
    "Дата аннулирования": ['propuska.CancelDate'],
    "global_id": ['propuska.global_id'],

    "section": ['sport.section'],
    "subsection": ['sport.subsection'],
    "title": ['sport.title'],
    "description": ['sport.description'],
    "start": ['sport.start'],
    "stop": ['sport.stop'],
    "address": ['sport.address'],
    "participants": ['sport.participants'],
    "секция": ['sport.section'],
    "подсекция": ['sport.subsection'],
    "название": ['sport.title'],
    "описание": ['sport.description'],
    "Дата начала": ['sport.start'],
    "Дата завершения": ['sport.stop'],
    "Аддрес": ['sport.address'],
    "участники": ['sport.participants'],

}
