tableAttributeList={
	#attribute		relation
	'department.name': 'department',
	'department.dId' : 'department',
	'department.buildingCode': 'department',
	'student.name': 'student',
	'student.sex' : 'student',
	'student.address' : 'student',
	'student.cgpa' : 'student',
	'student.phone' : 'student',
	'student.dId' : 'student',
	'student.sId' : 'student',

	'propuska.ID': 'propuska',
	'propuska.Series': 'propuska',
	'propuska.Number': 'propuska',
	'propuska.ValidFrom': 'propuska',
	'propuska.ValidTo': 'propuska',
	'propuska.Zone': 'propuska',
	'propuska.Status': 'propuska',
	'propuska.CancelDate': 'propuska',
	'propuska.global_id': 'propuska',

	'sport.section': 'sport',
	'sport.subsection': 'sport',
	'sport.title': 'sport',
	'sport.description': 'sport',
	'sport.start': 'sport',
	'sport.stop': 'sport',
	'sport.address': 'sport',
	'sport.participants': 'sport',

	'taxi.LicenseNumber': 'taxi',
	'taxi.global_id': 'taxi',
	'taxi.VehicleNumber': 'taxi',
	'taxi.INN': 'taxi',
	'taxi.OGRN': 'taxi',
	'taxi.BlankNumber': 'taxi',
	'taxi.VehicleBrand': 'taxi',
	'taxi.VehicleYear': 'taxi',
	'taxi.FullName': 'taxi',
	'taxi.ShortName': 'taxi',
	'taxi.LicenseDate': 'taxi',
	'taxi.LicenseEndDate': 'taxi',
	'taxi.ValidityDate': 'taxi',
	'taxi.EditDate': 'taxi',
	'taxi.Status': 'taxi',
	'taxi.VehicleModel': 'taxi',
	'taxi.LicenseNumber_en': 'taxi',
	'taxi.VehicleNumber_en': 'taxi',
	'taxi.INN_en': 'taxi',
	'taxi.OGRN_en': 'taxi',
	'taxi.BlankNumber_en': 'taxi',
	'taxi.VehicleBrand_en': 'taxi',
	'taxi.VehicleYear_en': 'taxi',
	'taxi.FullName_en': 'taxi',
	'taxi.ShortName_en': 'taxi',
	'taxi.LicenseDate_en': 'taxi',
	'taxi.LicenseEndDate_en': 'taxi',
	'taxi.ValidityDate_en': 'taxi',
	'taxi.EditDate_en': 'taxi',
	'taxi.Info_en': 'taxi',
	'taxi.Status_en': 'taxi',
	'taxi.VehicleModel_en': 'taxi',


}
